name: Update Website Content

on:
  schedule:
    - cron: '0 * * * *'  # This runs the job every hour
  workflow_dispatch:  # This allows manual triggering

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements

    - name: Run update script
      run: python updater.py
      env:
        CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update website content" && git push)